"""
HTML email template for call summary emails.
"""


def build_html_email(email_body_markdown: str, account_name: str, call_date: str) -> str:
    """
    Wrap the email body content in a clean HTML template.

    Args:
        email_body_markdown: The email content (already formatted by the Email Composer agent)
        account_name: Customer account name for the subject
        call_date: Date of the call

    Returns:
        Complete HTML email string
    """
    # Convert basic markdown to HTML
    html_body = _markdown_to_html(email_body_markdown)

    return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 700px;
            margin: 0 auto;
            padding: 20px;
        }}
        h2 {{
            color: #1a1a1a;
            border-bottom: 2px solid #e0e0e0;
            padding-bottom: 8px;
            margin-top: 28px;
        }}
        h3 {{
            color: #444;
            margin-top: 20px;
        }}
        ul, ol {{
            padding-left: 24px;
        }}
        li {{
            margin-bottom: 6px;
        }}
        strong {{
            color: #1a1a1a;
        }}
        .footer {{
            margin-top: 40px;
            padding-top: 16px;
            border-top: 1px solid #e0e0e0;
            color: #888;
            font-size: 0.85em;
        }}
        a {{
            color: #0066cc;
        }}
    </style>
</head>
<body>
    {html_body}
    <div class="footer">
        Generated by Call Intelligence AI
    </div>
</body>
</html>"""


def build_email_subject(account_name: str, call_date: str) -> str:
    """Build the email subject line."""
    return f"Call Summary: {account_name} - {call_date}"


def _markdown_to_html(text: str) -> str:
    """
    Simple markdown-to-HTML conversion for email content.
    Handles headers, bold, lists, and paragraphs.
    Not a full markdown parser — just enough for our email format.
    """
    import re

    lines = text.split("\n")
    html_lines = []
    in_list = False
    list_type = None  # "ul" or "ol"

    for line in lines:
        stripped = line.strip()

        # Close list if we hit a non-list line
        if in_list and not stripped.startswith("- ") and not re.match(r"^\d+\.\s", stripped) and stripped:
            html_lines.append(f"</{list_type}>")
            in_list = False
            list_type = None

        # Headers
        if stripped.startswith("### "):
            html_lines.append(f"<h3>{stripped[4:]}</h3>")
        elif stripped.startswith("## "):
            html_lines.append(f"<h2>{stripped[3:]}</h2>")
        elif stripped.startswith("# "):
            html_lines.append(f"<h1>{stripped[2:]}</h1>")
        # Unordered list
        elif stripped.startswith("- "):
            if not in_list or list_type != "ul":
                if in_list:
                    html_lines.append(f"</{list_type}>")
                html_lines.append("<ul>")
                in_list = True
                list_type = "ul"
            html_lines.append(f"<li>{_inline_format(stripped[2:])}</li>")
        # Ordered list
        elif re.match(r"^\d+\.\s", stripped):
            if not in_list or list_type != "ol":
                if in_list:
                    html_lines.append(f"</{list_type}>")
                html_lines.append("<ol>")
                in_list = True
                list_type = "ol"
            content = re.sub(r"^\d+\.\s", "", stripped)
            html_lines.append(f"<li>{_inline_format(content)}</li>")
        # Horizontal rule
        elif stripped == "---":
            html_lines.append("<hr>")
        # Empty line
        elif not stripped:
            if in_list:
                html_lines.append(f"</{list_type}>")
                in_list = False
                list_type = None
        # Regular paragraph
        else:
            html_lines.append(f"<p>{_inline_format(stripped)}</p>")

    # Close any open list
    if in_list:
        html_lines.append(f"</{list_type}>")

    return "\n".join(html_lines)


def _inline_format(text: str) -> str:
    """Apply inline markdown formatting (bold, links)."""
    import re
    # Bold: **text**
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    # Links: [text](url)
    text = re.sub(r"\[(.+?)\]\((.+?)\)", r'<a href="\2">\1</a>', text)
    return text
