"""
Tests for the email templates module.
These tests don't require API keys or external services.
"""

from src.email.templates import build_html_email, build_email_subject, _markdown_to_html


class TestEmailSubject:
    def test_basic_subject(self):
        subject = build_email_subject("Acme Corp", "2026-02-06")
        assert subject == "Call Summary: Acme Corp - 2026-02-06"

    def test_subject_with_special_chars(self):
        subject = build_email_subject("O'Reilly & Partners", "2026-02-06")
        assert "O'Reilly & Partners" in subject


class TestMarkdownToHtml:
    def test_headers(self):
        html = _markdown_to_html("## Executive Summary")
        assert "<h2>Executive Summary</h2>" in html

    def test_bold_text(self):
        html = _markdown_to_html("This is **bold** text")
        assert "<strong>bold</strong>" in html

    def test_unordered_list(self):
        html = _markdown_to_html("- Item one\n- Item two")
        assert "<ul>" in html
        assert "<li>Item one</li>" in html
        assert "<li>Item two</li>" in html

    def test_ordered_list(self):
        html = _markdown_to_html("1. First\n2. Second")
        assert "<ol>" in html
        assert "<li>First</li>" in html

    def test_horizontal_rule(self):
        html = _markdown_to_html("---")
        assert "<hr>" in html

    def test_links(self):
        html = _markdown_to_html("[Click here](https://example.com)")
        assert '<a href="https://example.com">Click here</a>' in html


class TestBuildHtmlEmail:
    def test_contains_body_content(self):
        html = build_html_email("## Summary\n- Key point", "Acme", "2026-02-06")
        assert "Summary" in html
        assert "Key point" in html

    def test_contains_footer(self):
        html = build_html_email("Content here", "Acme", "2026-02-06")
        assert "Generated by Call Intelligence AI" in html

    def test_is_valid_html(self):
        html = build_html_email("Test content", "Acme", "2026-02-06")
        assert html.startswith("<!DOCTYPE html>")
        assert "</html>" in html
